import {AdditionalAlgorithmicAnalysisParameters, StatisticFields} from "./statistic-fields-enum";

export const displayNames: Record<string, string> = {
  [StatisticFields.AbdomenHurts]: 'Боль в животе',
  [StatisticFields.BloodDischarge]: 'Кровянистые выделения',
  [StatisticFields.Nausea]: 'Тошнота',
  [StatisticFields.UrgeToPuke]: 'Рвотные позывы',
  [StatisticFields.Temperature]: 'Температура',
  [StatisticFields.SystolicPressure]: 'Верхнее давление',
  [StatisticFields.DiastolicPressure]: 'Нижнее давление',
  [StatisticFields.HeartRate]: 'Пульс',
  [StatisticFields.GlucoseLevel]: 'Глюкоза в крови',
  [StatisticFields.HemoglobinLevel]: 'Гемоглобин',
  [StatisticFields.Saturation]: 'Сатурация',
  [StatisticFields.Uro]: 'URO',
  [StatisticFields.Bld]: 'BLD',
  [StatisticFields.Bil]: 'BIL',
  [StatisticFields.Ket]: 'KET',
  [StatisticFields.Leu]: 'LEU',
  [StatisticFields.Glu]: 'GLU',
  [StatisticFields.Pro]: 'PRO',
  [StatisticFields.Ph]: 'PH',
  [StatisticFields.Nit]: 'NIT',
  [StatisticFields.Sg]: 'SG',
  [StatisticFields.Vc]: 'VC',
  [StatisticFields.Pt]: 'PT',
  [StatisticFields.Aptt]: 'APTT',
  [StatisticFields.Inr]: 'INR',
  [StatisticFields.BloodCoagulation]: 'Свертываемость крови',
  [StatisticFields.OxygenLevel]: 'Уровень кислорода',
  [StatisticFields.HasOrvi]: 'Симптомы ОРВИ',
  [StatisticFields.HasUnordinaryTemp]: 'Повышение температуры выше 37.2°',
  [StatisticFields.UnordinaryTempOccurrences]: 'Частота повышения температуры',
  [StatisticFields.UnordinaryBloodPressure]: 'Повышение артериального давления',
  [StatisticFields.HasGynecologicalSymptoms]: 'Гинекологические симптомы',
  [StatisticFields.HasUnordinaryUrine]: 'Отклонения в анализе мочи',
  [StatisticFields.HasSwelling]: 'Отёки',
  [StatisticFields.WaterConsumed]: 'Потребление жидкости',
  [StatisticFields.Stool]: 'Регулярность стула',
  [StatisticFields.Urination]: 'Мочеиспускание',
  [StatisticFields.WeightAdded]: 'Прибавка веса за неделю',
  [StatisticFields.PregnancyWeek]: 'Неделя беременности',

  [AdditionalAlgorithmicAnalysisParameters.TestParam]: 'Тестовый параметр',
};

export const hints: Record<string, string> = {
  [StatisticFields.AbdomenHurts]: 'Боль в животе',
  [StatisticFields.BloodDischarge]: 'Кровянистые выделения',
  [StatisticFields.Nausea]: 'Тошнота',
  [StatisticFields.UrgeToPuke]: 'Рвотные позывы',
  [StatisticFields.Temperature]: 'Температура',
  [StatisticFields.SystolicPressure]: 'Верхнее давление',
  [StatisticFields.DiastolicPressure]: 'Нижнее давление',
  [StatisticFields.HeartRate]: 'Пульс',
  [StatisticFields.GlucoseLevel]: 'Глюкоза в крови',
  [StatisticFields.HemoglobinLevel]: 'Гемоглобин',
  [StatisticFields.Saturation]: 'Сатурация',
  [StatisticFields.Uro]: 'URO',
  [StatisticFields.Bld]: 'BLD',
  [StatisticFields.Bil]: 'BIL',
  [StatisticFields.Ket]: 'KET',
  [StatisticFields.Leu]: 'LEU',
  [StatisticFields.Glu]: 'GLU',
  [StatisticFields.Pro]: 'PRO',
  [StatisticFields.Ph]: 'PH',
  [StatisticFields.Nit]: 'NIT',
  [StatisticFields.Sg]: 'SG',
  [StatisticFields.Vc]: 'VC',
  [StatisticFields.Pt]: 'PT',
  [StatisticFields.Aptt]: 'APTT',
  [StatisticFields.Inr]: 'INR',
  [StatisticFields.BloodCoagulation]: 'Свертываемость крови',
  [StatisticFields.OxygenLevel]: 'Уровень кислорода',
  [StatisticFields.HasOrvi]: 'Симптомы ОРВИ',
  [StatisticFields.HasUnordinaryTemp]: 'Повышение температуры выше 37.2°',
  [StatisticFields.UnordinaryTempOccurrences]: 'Частота повышения температуры',
  [StatisticFields.UnordinaryBloodPressure]: 'Повышение артериального давления',
  [StatisticFields.HasGynecologicalSymptoms]: 'Гинекологические симптомы',
  [StatisticFields.HasUnordinaryUrine]: 'Отклонения в анализе мочи',
  [StatisticFields.HasSwelling]: 'Отёки',
  [StatisticFields.WaterConsumed]: 'Потребление жидкости',
  [StatisticFields.Stool]: 'Регулярность стула',
  [StatisticFields.Urination]: 'Мочеиспускание',
  [StatisticFields.WeightAdded]: 'Прибавка веса за неделю',
  [StatisticFields.PregnancyWeek]: 'Неделя беременности',

  [AdditionalAlgorithmicAnalysisParameters.TestParam]: 'Тестовый параметр',
};

