export enum StatisticFields {
  AbdomenHurts = 'AbdomenHurts',
  BloodDischarge = 'BloodDischarge',
  Nausea = 'Nausea',
  UrgeToPuke = 'UrgeToPuke',
  Temperature = 'Temperature',
  SystolicPressure = 'SystolicPressure',
  DiastolicPressure = 'DiastolicPressure',
  HeartRate = 'HeartRate',
  GlucoseLevel = 'GlucoseLevel',
  HemoglobinLevel = 'HemoglobinLevel',
  Saturation = 'Saturation',
  Uro = 'Uro',
  Bld = 'Bld',
  Bil = 'Bil',
  Ket = 'Ket',
  Leu = 'Leu',
  Glu = 'Glu',
  Pro = 'Pro',
  Ph = 'Ph',
  Nit = 'Nit',
  Sg = 'Sg',
  Vc = 'Vc',
  Pt = 'Pt',
  Aptt = 'Aptt',
  Inr = 'Inr',
  BloodCoagulation = 'BloodCoagulation',
  OxygenLevel = 'OxygenLevel',

  HasOrvi = 'HasOrvi',
  HasUnordinaryTemp = 'HasUnordinaryTemp',
  UnordinaryTempOccurrences = 'UnordinaryTempOccurrences',
  UnordinaryBloodPressure = 'UnordinaryBloodPressure',
  HasGynecologicalSymptoms = 'HasGynecologicalSymptoms',
  HasUnordinaryUrine = 'HasUnordinaryUrine',
  HasSwelling = 'HasSwelling',
  WaterConsumed = 'WaterConsumed',
  Stool = 'Stool',
  Urination = 'Urination',
  WeightAdded = 'WeightAdded',
  PregnancyWeek = 'PregnancyWeek',
}

export enum AdditionalAlgorithmicAnalysisParameters {
  TestParam = 'TestParam'
}
