// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PregnancyAppBackend.Persistance;

#nullable disable

namespace PregnancyAppBackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250503100626_FixedParameterValuesDb")]
    partial class FixedParameterValuesDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PregnancyAppBackend.Entities.AlgorithmicAnalysisParameterValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.HasIndex("UserId", "ParameterId")
                        .IsUnique();

                    b.ToTable("AlgorithmicAnalysisParameterValues");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.DailySurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AbdomenHurts")
                        .HasColumnType("bit");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("Aptt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Bil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Bld")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BloodCoagulation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BloodDischarge")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiastolicPressure")
                        .HasColumnType("int");

                    b.Property<decimal?>("Glu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GlucoseLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("HemoglobinLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Inr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Leu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Nausea")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Nit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OxygenLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Saturation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SystolicPressure")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("UrgeToPuke")
                        .HasColumnType("int");

                    b.Property<decimal?>("Uro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Vc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailySurveys", t =>
                        {
                            t.HasCheckConstraint("CK_DailySurvey_BloodPressure", "[BloodPressure] LIKE '[0-9][0-9]/[0-9][0-9]' OR [BloodPressure] LIKE '[0-9][0-9][0-9]/[0-9][0-9]' OR [BloodPressure] LIKE '[0-9][0-9]/[0-9][0-9][0-9]' OR [BloodPressure] LIKE '[0-9][0-9][0-9]/[0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.MedicalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AbortionAmount")
                        .HasColumnType("int");

                    b.Property<string>("AllergicReactions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BloodGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnduredCovid")
                        .HasColumnType("int");

                    b.Property<string>("GynecologicalDiseases")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("HereditaryDiseasesString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("HereditaryDiseases");

                    b.Property<bool>("IsConsumingAlcohol")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmoking")
                        .HasColumnType("bit");

                    b.Property<int?>("MiscarriageAmount")
                        .HasColumnType("int");

                    b.Property<int>("PregnancyAmount")
                        .HasColumnType("int");

                    b.Property<int?>("PrematureBirthAmount")
                        .HasColumnType("int");

                    b.Property<int>("PreviousBirthType")
                        .HasColumnType("int");

                    b.Property<int>("RhesusFactor")
                        .HasColumnType("int");

                    b.Property<string>("SomaticDiseases")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Thermometer")
                        .HasColumnType("int");

                    b.Property<int>("Tonometer")
                        .HasColumnType("int");

                    b.Property<string>("UndergoneOperations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.ObservationParameterNorm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("LowerBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("UpperBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.HasIndex("UserId");

                    b.ToTable("ObservationParameterNorms");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DefaultLowerBoundValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DefaultUpperBoundValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.PatientDoctorCommunicationLink", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommunicationLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("MeetingScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("PatientDoctorCommunicationLinks");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.ApiClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApiClaims");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.RoleApiClaim", b =>
                {
                    b.Property<Guid>("ApiClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApiClaimId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleApiClaims", (string)null);
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfChangeOfAccessRights")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.UserCommonInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrustedPersonEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrustedPersonFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrustedPersonPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCommonInfos");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.WeeklySurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GynecologicalSymptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasGynecologicalSymptoms")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOrvi")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSwelling")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUnordinaryTemp")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUnordinaryUrine")
                        .HasColumnType("bit");

                    b.Property<string>("OrviSymptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PregnancyWeek")
                        .HasColumnType("int");

                    b.Property<int>("Stool")
                        .HasColumnType("int");

                    b.Property<string>("SwellingDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UnordinaryBloodPressure")
                        .HasColumnType("int");

                    b.Property<int?>("UnordinaryTempOccurrences")
                        .HasColumnType("int");

                    b.Property<int>("Urination")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WaterConsumed")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightAdded")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklySurveys");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.AlgorithmicAnalysisParameterValue", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.DailySurvey", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithMany("DailySurveys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.MedicalHistory", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.ObservationParameterNorm", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parameter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.PatientDoctorCommunicationLink", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.RoleApiClaim", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.ApiClaim", "ApiClaim")
                        .WithMany("RoleApiClaims")
                        .HasForeignKey("ApiClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PregnancyAppBackend.Entities.Security.Role", "Role")
                        .WithMany("RoleApiClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiClaim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.UserRole", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.UserCommonInfo", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithOne()
                        .HasForeignKey("PregnancyAppBackend.Entities.UserCommonInfo", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.WeeklySurvey", b =>
                {
                    b.HasOne("PregnancyAppBackend.Entities.Security.User", "User")
                        .WithMany("WeeklySurveys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.ApiClaim", b =>
                {
                    b.Navigation("RoleApiClaims");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.Role", b =>
                {
                    b.Navigation("RoleApiClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PregnancyAppBackend.Entities.Security.User", b =>
                {
                    b.Navigation("DailySurveys");

                    b.Navigation("UserRoles");

                    b.Navigation("WeeklySurveys");
                });
#pragma warning restore 612, 618
        }
    }
}
